---
title: "Ratings Data Analysis"
author: "Nelson Tian, Eve Higby"
date: "March 3, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Set working directory in console
```

```{r packages, results="hide", message = FALSE}
# for demographics
library(Rmisc)
# for data manipulation
library(dplyr)
library(data.table)
library(tidyr)
# for plots
library(ggplot2)
library(ggpubr)
# for ANOVA
library(car)
# for correlation scatters
library(ggpubr)
library(gridExtra)
# for mixed effects model
library(lme4)
library(ordinal)
```


```{r ratings data}
# This chunk will deal with reading in and cleaning up the ratings data

# Read in cleaned up ratings data file
ratings <- read.csv("ratings.csv") # 32680 obs
# ratings <- read.csv("ratings2.csv")
ecuador <- read.csv("Ecuador_ratings.csv") # 6080 obs

# Remove 3 Ps with no distinction between PsCaus and Trans sentences
ratings <- subset(ratings, subject != 207 & subject != 304 & subject != 318) #31540 obs

# Remove 2 Ps whose English was too high for the monolingual group
ratings <- subset(ratings, subject != 302 & subject != 319) #30780 obs

# Subset heritage speakers, early bilinguals, and controls
  # All HSs
HS <- subset(ratings, subject %in% c(101, 103, 104, 105, 107, 109, 111, 112, 113, 115, 117, 
                                     209, 214, 216, 219)) 

# All HS with good ERP data
#HS2 <- subset(ratings, subject %in% c(101, 103, 107, 111, 112, 113, 115, 117, 214, 219)) 

  # Change group number to 1 for all
HS$group <- 1
#HS2$group <- 1

# Early bilinguals that are not heritage speakers
EB <- subset(ratings, subject %in% c(102,108,110,114,116,118:122,203,213,215,222))

# change group number to 2 for all
EB$group <- 2

# Late Bilinguals are group 2 that aren't used yet
LB <- subset(ratings, subject %in% c(201,202,204,205,206,208,210,211,212,218,220,221))

LB$group <- 3

  # All Spanish monolinguals
SM <- subset(ratings, group == 3)

# Spanish monolinguals with ERP data
#SM2 <- subset(ratings, subject %in% c(301, 303, 304, 305, 306, 308, 309, 311, 312, 314, 315, 316, 317, 318, 322))

# Change group number to 3 for all
SM$group <- 4
#SM2$group <- 3

# all English monolinguals
EM <- subset(ratings, subject %in% c(401:412,414:422,425,427:429))
EM$group <- 5

# Combine HS, EB, LB and SM
# not SM
all <- rbind(HS,EB)
all <- rbind(all,LB)
all <- rbind(all,SM)
all <- rbind(all,EM)
  # should be 29 Ps (11020 obs)

# Set up factor variables
# Make subject, group, and condition factors
all <- within(all, {
  subject <- factor(subject)
  group <- factor(group)
  condition <- factor(condition)
  sentFrame <- factor(sentFrame)
  condition <- factor(condition)
  stimCode <- factor(stimCode)
  block <- factor(block)
  verb <- factor(verb)
})


# Label condition and group levels
all$condition <- factor(all$condition, levels = c('10', '20', '40', '30', '50', '60', '70'), 
                            labels=c("10"="Causative", "20"="Pseudo-causative", "40"="Transitive", 
                                     "30"="Intransitive-D", "50"="Intransitive-S", "60"="Intransitive-PC", 
                                     "70" = "Filler"))

all$group <- factor(all$group, levels = c('1', '2','3','4','5'), 
                        labels=c("1"="Heritage Speakers","2"="Early Bilinguals", "3"="Late Bilinguals",
                                 "4"="Spanish Controls","5"="English Controls"))

# Ecuador data
ecuador$subject <- ecuador$subject + 300 
#ecuador$sex <- factor(ecuador$sex, levels = c("Femenino","Masculino"),
#                      labels = c("Femenino"="Female", "Masculino"="Male"))
ecuador$condition <- factor(ecuador$condition, levels = c("Causative","Filler","Intransitive (Direct Object)",
                                                          "Intransitive (Subject)","Intransitive Pseudo-Causative (Direct Object)",
                                                          "Pseudo-Causative","Transitive (Animate Direct Object)"),
                            labels = c("Causative"="Causative","Filler"="Filler","Intransitive (Direct Object)"="Intransitive-D",
                                       "Intransitive (Subject)"="Intransitive-S","Intransitive Pseudo-Causative (Direct Object)"="Intransitive-PC",
                                       "Pseudo-Causative"="Pseudo-causative","Transitive (Animate Direct Object)"="Transitive"))
# don't need hand or block, setting to "NA" to make merging easier
ecuador$hand <- "NA"
ecuador$block <- "NA"
ecuador$group <- factor("Ecuador Spanish")
ecuador <- within(ecuador, {
  subject <- factor(subject)
  sentFrame <- factor(sentFrame)
  condition <- factor(condition)
  stimCode <- factor(stimCode)
  verb <- factor(verb)
})
ecuador <- ecuador %>%
  select(subject,age,group,hand,sex,stimNum,condition,rating,rt,sentFrame,stimCode,block,verb)

all <- rbind(all, ecuador) 
    # should have 17100 obs (45 participants)

## NEW CODE
# Remove filler condition
all <- subset(all, condition != "Filler") 
    # should have 12960 obs

# Add verb labels
all$verb <- factor(all$verb, levels = c('1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16',
                                        '18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33',
                                        '35','36','37','38','39','40','41','42','43','44','45','46','47','48','50','51'),
                   labels=c("1"="trotar/jog", "2"="andar/hike", "3"="deambular/stroll", 
                            "4"="transitar/trek", "5"="avanzar/advance", "6"="gatear/crawl", 
                            "7"="escalar/climb", "8"="caminar/walk", "9"="brincar/jump",
                            "10"="marchar/march", "11"="correr/run", "12"="nadar/swim",
                            "13"="volar/fly", "14"="bailar/dance", "15"="saltar/leap",
                            "16"="desfilar/parade", "18"="corretear/chase", "19"="escoltar/escort",
                            "20"="apresurar/hurry", "21"="guiar/guide", "22"="dirigir/direct",
                            "23"="arrastrar/drag", "24"="jalar/pull", "25"="acompanar/accompany",
                            "26"="acariciar/pet", "27"="transportar/transport", "28"="observar/observe",
                            "29"="cargar/carry", "30"="mandar/send", "31"="perseguir/follow",
                            "32"="lanzar/throw", "33"="conducir/drive", "35"="sudar/sweat",
                            "36"="estornudar/sneeze", "37"="suspirar/sigh", "38"="roncar/snore",
                            "39"="tambalearse/wobble", "40"="gemir/growl", "41"="llorar/cry",
                            "42"="bostezar/yawn", "43"="caer/fall", "44"="temblar/shiver",
                            "45"="cojear/limp", "46"="dormir/sleep", "47"="vagar/wander",
                            "48"="sollozar/sob", "50"="respirar/breathe", "51"="reir/laugh"))

# switch order of English Controls (5th group) and Ecuador Spanish (6th group)
all$group = factor(all$group, levels = c(levels(all$group)[1:4], levels(all$group)[6], levels(all$group)[5]))

# make a resulting excel file called "ratings_full.csv"
write.csv(all, "ratings_full.csv")
```

```{r verb data}
# this chunk creates an auxillary dataframe with frequencies per verb

# ratings data chunk only needs to be run once
# can read from resulting ratings_full.csv instead after the first time
if(!exists("all", inherits = FALSE))
{
  all <- read.csv("ratings_full.csv")
  all$group <- factor(all$group, levels = c("Heritage Speakers","Early Bilinguals",
                                            "Late Bilinguals","Spanish Controls",
                                            "Ecuador Spanish","English Controls"))
}

# make a separate dataframe for verbs and combine them with frequencies
allverb <- levels(all$verb)
allverb <- data.frame(verb = allverb)

# remove everything before the '/' for English verb (e.g. "trotar/jog" becomes "jog")
allverb$engverb <- gsub(".*/", "", allverb$verb)
# remove everything before the '/' for the Spanish verb
allverb$spnverb <- gsub("/.*", "", allverb$verb)

# excel file with English verbs and frequencies
eng <- read.csv("engfreq.csv")
colnames(eng) <- c("engverb", "class", "word", "wordfreq", "engfreq", "ID")
# only need one instance of each engverb and engfreq
eng <- eng[,c("engverb","engfreq")]
eng <- unique(eng)
# rank variable that ranks by frequency
eng <- eng[order(-eng$engfreq),]
eng$engrank <- c(1:length(eng$engfreq))

# do the same for spanish
spn <- read.csv("spnfreq.csv")
colnames(spn) <- c("spnverb", "freq", "ppm", "spnfreq","zipf")
# rank variable that ranks by frequency
spn <- spn[order(-spn$zipf),]
spn$spnrank <- c(1:length(spn$spnfreq))
# only need spnverb and spnverb, and spnrank, and zipf
spn <- spn[,c("spnverb","spnfreq","spnrank","ppm","zipf")]

allverbn <- merge(x = allverb, y = eng, by = "engverb", all.x = TRUE)
allverbn <- merge(x = allverbn, y = spn, by = "spnverb", all.x = TRUE)

# # rank each word by frequency
# allverbn <- allverbn[order(-allverbn$engfreq),]
# allverbn$rank <- c(1:length(allverbn$verb))

# change to factors
allverbn <- within(allverbn, {
  engverb <- factor(engverb)
  spnverb <- factor(spnverb)
})
```

```{r condition filtering}
# this chunk creates separate dataframes based on condition for the mean ratings per verb and group

# function to make a plot-ready dataset per condition
cond_filter <- function(df, cond)
{
  df_new <- df %>%
    # filter by desired condition
    filter(condition == cond) %>%
    # get mean ratings per each group and verb combination
    group_by(.dots=c("group", "verb")) %>%
    summarise_all(funs(mean(rating, na.rm = TRUE))) %>%
    # get rid of unnecessary columns, keep only these 3
    select(group, verb, rating)
  
  # merge new columns rank and lemmafreq into the df
  df_new <- merge(x = df_new, y = allverbn, by = "verb", all.x = TRUE)
  
  df_new <- df_new[order(df_new$engrank),]
  # # reorder the factor levels of each verb based on rank
  # # df_new$verb = factor(df_new$verb,levels(df_new$verb)[unique(df_new$verb)])
  df_new$verb = factor(df_new$verb,levels = unique(df_new$verb))
  
  return(df_new)
}

# call the filter for each condition
caus <- cond_filter(all, "Causative")
pscaus <- cond_filter(all, "Pseudo-causative")
trans <- cond_filter(all, "Transitive")
# we don't need the rest
# intransD <- cond_filter(all, "Intransitive-D")
# intransS <- cond_filter(all, "Intransitive-S")
# intransPC <- cond_filter(all, "Intransitive-PC")
# filler <- cond_filter(all, "Filler")

# want global average per verb across all non-english groups
verbavg <- caus %>%
  filter(group != "English Controls") %>%
  select(verb, rating)
verbavg <- aggregate(verbavg[,2], list(verbavg$verb), mean)
names(verbavg) <- c("verb", "avgrating")
caus <- merge(caus, verbavg, by = "verb", all = TRUE)
# rank by global average (reorder factor of verb)
caus <- caus[order(-caus$avgrating),]
caus$verb = factor(caus$verb,levels = unique(caus$verb))
```

```{r ranked csv export}
# this chunk creates an excel file for each condition containing verbs and ratings sorted for each group

colname <- c("HSverb", "EBverb", "LBverb", "SCverb", "ESverb", "ECverb")
# rank each verb by rating PER GROUP
ratingpergroup <- function(df, colname)
{
  # for each group
  for(i in 1:length(levels(df$group)))
  #for(i in 1:j)
  {
    # one group at a time
    df_temp <- df %>%
      filter(group == levels(df$group)[i]) %>%
      select(group, rating, verb)
    # want rating per verb, spread uses per-group name as rating column
    df_temp <- spread(df_temp, key = group, value = rating)
    df_temp <- df_temp[,c(2,1)]
    # rename the verb columns to include group abbreviations
    colnames(df_temp)[2] <- paste(colname[i])
    # order them by highest to lowest rating
    df_temp <- df_temp[order(-df_temp[,1]),]
    df_temp$rank <- c(1:16)
    # make into data.table for easy merging
    df_temp <- data.table(df_temp, key = "rank")
    # if first loop, make a new dataframe
    if(i == 1)
    {
      df_new <- df_temp
    }
    # else, merge the temp into the created dataframe
    else
    {
      df_new <- df_new[df_temp]
    }
  }
  #  don't need rank anymore now that the table is finished
  df_new <- df_new %>%
    select(-rank)
  # df_new has the verbs ranked by rating per group
  return(df_new)
}
causgrouped <- ratingpergroup(caus, colname)
pscausgrouped <- ratingpergroup(pscaus, colname)
transgrouped <- ratingpergroup(trans, colname)
# export this to csv
write.csv(causgrouped, file = "causratingranked.csv")
write.csv(pscausgrouped, file = "pscausgratingranked.csv")
write.csv(transgrouped, file = "transratingranked.csv")
```

```{r item plots}
# this chunk plots each verb with x as group and y as rating

# make 16 color gradient from red to blue (one color per verb)
redtoblue <- colorRampPalette(c("firebrick1", "deepskyblue"))
# check hexadecimal values
redtoblue(16)
# check the gradient
plot(rep(1,16), col = redtoblue(16), pch = 16, cex = 2)

# plot one per condition
causplot <- ggplot(caus, aes(x = group, y = rating, color = verb, group = verb)) +
  geom_line() +
  geom_point() +
  xlab("Group") +
  ylab("Rating") +
  ggtitle("Average Ratings for Causative Verbs") +
  scale_y_continuous(limits = c(1,5)) +
  scale_color_manual(values = redtoblue(16)) +
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
pscausplot <- ggplot(pscaus, aes(x = group, y = rating, color = verb, group = verb)) +
  geom_line() +
  geom_point() +
  xlab("Group") +
  ylab("Rating") +
  ggtitle("Average Ratings for Ps-Causative Verbs, Ranked by Frequency") +
  scale_y_continuous(limits = c(1,5)) +
  scale_color_manual(values = redtoblue(16)) +
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
transplot <- ggplot(trans, aes(x = group, y = rating, color = verb, group = verb)) +
  geom_line() +
  geom_point() +
  xlab("Group") +
  ylab("Rating") +
  ggtitle("Average Ratings for Transitive Verbs, Ranked by Frequency") +
  scale_y_continuous(limits = c(1,5)) +
  scale_color_manual(values = redtoblue(16)) +
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()

# print the 3 plots
causplot; pscausplot; transplot
```

```{r item plot export}
# save recently made plots in pdf and png format

# set up the pdf to save to
pdf("ratings6gsorted.pdf", onefile = TRUE)
# print the 3 plots INTO the pdf
causplot
pscausplot
transplot
# close the pdf
dev.off()

# save each to png files
ggsave("caus_ratings6gavgverb.png", causplot, width = 8, height = 6)
ggsave("pscaus_ratings6gsorted.png", pscausplot, width = 9, height = 6)
ggsave("trans_ratings6gsorted.png", transplot, width = 9, height = 6)
```


```{r 3 group item plot}
# this chunk makes the same rating-by-group per verb plot as the previous chunk, but with 3 groups and one condition (caus)
# make a plot for each bilingual group with the two monolingual groups

# examine caus plots with only 3 groups each for closer inspection
# list of bilingual groups (including Spanish Control)
BIL_list <- c("Heritage Speakers","Early Bilinguals","Late Bilinguals", "Spanish Controls")
# plot each bilingual with Spanish (ES) on one end and English (EC) on the other
for(bilingual in BIL_list)
{
  # make a set with monolinguals centered around bilingual group of choice
  caus_temp <- caus %>%
    filter(group %in% c(bilingual,"Ecuador Spanish","English Controls"))
  # reorder group factor to Spanish, [Bilingual], English
  caus_temp$group <- factor(caus_temp$group, levels = c("Ecuador Spanish",
                                                        bilingual,
                                                        "English Controls"))
  # plot each bilingual vs monolinguals
  plot_title <- paste("Causative Verbs, Monolinguals vs. ", bilingual, sep = "")
  BIL_plot <- ggplot(caus_temp, aes(x = group, y = rating, color = verb, group = verb)) +
    geom_line() +
    geom_point() +
    xlab("Group") +
    ylab("Rating") +
    ggtitle(plot_title) +
    scale_color_manual(values = redtoblue(16)) +
    theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
    theme_classic()
  print(BIL_plot)
}
```

```{r 3 group item plot export}
# export the recently made plots to png

for(bilingual in BIL_list)
{
  # save each plot to png
  # change the space in bilingual group to underscore
  group_name <- gsub('([[:punct:]])|\\s+','_',bilingual)
  # make the title lowercase
  group_name <- sapply(group_name, tolower)
  # title should be caus_ratings_[group_name] (e.g. "caus_ratings_early_bilinguals.png")
  png_title <- paste("caus_ratings_", group_name, ".png", sep = "")
  ggsave(png_title, BIL_plot, width = 8, height = 6)
}
```


```{r demographics}
# this chunk explores demographic info on the participants (age, sex, etc.)

# demographic info into a csv file (age, n, mean rating)
demo <- all %>%
  group_by(group) %>%
  summarise(n = n(),
            subjects = length(unique(subject)),
            min_age = min(age),
            max_age = max(age),
            avg_age = mean(age)
            #avg_rating = mean(rating, na.rm = TRUE)
            )
colnames(demo) = c("Group", "n", "Subjects", "Min Age", "Max Age", "Mean Age")
write.csv(demo,"demo.csv")


# Summarize age by participant
part.age <- summarySE(all, measurevar="age", 
                      groupvars = c("subject", "group"),
                      na.rm = TRUE)

# Summarize age by group
group.age <- summarySE(part.age, measurevar="age", 
                       groupvars = c("group"),
                       na.rm = TRUE)

# Box plot
part.age.plt <- ggplot(part.age, aes(x=group, y=age, fill=group)) + 
  geom_boxplot() +
  scale_fill_brewer(palette = "Paired") +
  xlab("Group") + ylab("Age") +
  ggtitle("Ages across Groups") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
part.age.plt

# Summarize sex by participant
part.sex <- summarySE(all, measurevar="rating", 
                      groupvars = c("subject", "group", "sex"),
                      na.rm = TRUE)

# Bar plot
part.sex.plt <- ggplot(part.sex, aes(sex, group = group, fill=group)) +
  geom_bar(
    colour = "black", # contour around each bar
    size = 0.7 # width of the contour line
  ) + 
  scale_fill_brewer(palette = "Paired") +
  xlab("Sex") + ylab("N") +
  ggtitle("Sex Distributions across Groups") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
part.sex.plt

### Ratings

cond.colors <- c("indianred3", "steelblue3", "mediumseagreen", "burlywood1", "burlywood2", "burlywood3", "lightsalmon")

# Mean rating per participant
pRat <- summarySE(all, measurevar="rating", 
                  groupvars = c("subject", "group"),
                  na.rm = TRUE)

# Bar chart
pRat.plt <- ggplot(pRat, aes(x = subject, y = rating)) +
  geom_bar(stat = "identity", 
           position = "dodge", 
           fill = "slategray3",
           colour = "black", # contour around each bar
           size = 0.7 # width of the contour line
  ) + 
  coord_cartesian(ylim=c(1.0, 5.0)) +
  xlab("Participant") + ylab("Mean Rating") +
  ggtitle("Mean Rating for each Participant") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
pRat.plt

# Mean rating per participant and condition
pRat.cond <- summarySE(all, measurevar="rating", 
                       groupvars = c("subject", "group", "condition"),
                       na.rm = TRUE)

# Box plot
pRat.cond.plt <- ggplot(pRat.cond, aes(x=condition, y=rating, fill=condition)) + 
  geom_boxplot() + 
  scale_fill_manual(values=cond.colors) +
  xlab("Condition") + ylab("Mean Rating") +
  ggtitle("Mean Rating by Condition") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
pRat.cond.plt

# Mean rating by condition
rat.cond <- summarySE(pRat.cond, measurevar="rating", 
                      groupvars = c("condition"),
                      na.rm = TRUE)

# Bar plot
rat.cond.plt <- ggplot(rat.cond, aes(x = condition, y = rating, fill = condition)) +
  geom_bar(stat = "identity", 
           position = "dodge", 
           colour = "black", # contour around each bar
           size = 0.7 # width of the contour line
  ) + 
  scale_fill_manual(values=cond.colors) +
  coord_cartesian(ylim=c(1.0, 5.0)) +
  geom_errorbar(aes(ymin=rating-ci, ymax=rating+ci), width=.2,
                position = position_dodge(0.9)) +
  xlab("Condition") + ylab("Mean Rating") +
  ggtitle("Mean Rating for each Condition") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
rat.cond.plt

# Mean rating per group and condition
gRat.cond <- summarySE(pRat.cond, measurevar="rating", 
                       groupvars = c("group", "condition"),
                       na.rm = TRUE)

# Bar plot
gRat.cond.plt <- ggplot(gRat.cond, aes(x = condition, y = rating, fill=group, group=group)) +
  geom_bar(stat = "identity", 
           position = "dodge", 
           colour = "black", # contour around each bar
           size = 0.7 # width of the contour line
  ) + 
  scale_fill_brewer(palette = "Paired") +
  coord_cartesian(ylim=c(1.0, 5.0)) +
  geom_errorbar(aes(ymin=rating-ci, ymax=rating+ci), width=.2,
                position = position_dodge(0.9)) +
  xlab("Condition") + ylab("Mean Rating") +
  ggtitle("Mean Rating for each Group & Condition") + 
  theme(plot.title = element_text(hjust=0.5, lineheight=.8, face="bold")) +
  theme_classic()
gRat.cond.plt


### 3 Conditions

# Subset Causative, Pseudo-causative, & Transitive
all.3cond <- subset(all, condition %in% c("Causative", "Pseudo-causative", "Transitive")) 

# Mean rating per participant and condition
pRat.3cond <- summarySE(all.3cond, measurevar="rating", 
                        groupvars = c("subject", "group", "condition"),
                        na.rm = TRUE)

# Mean rating per participant and condition
gRat.3cond <- summarySE(pRat.3cond, measurevar="rating", 
                        groupvars = c("group", "condition"),
                        na.rm = TRUE)

# Bar plot
gRat.3cond.plt <- ggplot(gRat.3cond, aes(x = condition, y = rating, fill=group, group=group)) +
  geom_bar(stat = "identity", 
           position = "dodge", 
           colour = "black", # contour around each bar
           size = 0.7 # width of the contour line
  ) + 
  scale_fill_brewer(palette = "Paired") +
  coord_cartesian(ylim=c(1.0, 5.0)) +
  geom_errorbar(aes(ymin=rating-ci, ymax=rating+ci), width=.2,
                position = position_dodge(0.9)) +
  xlab("Condition") + ylab("Mean Rating") +
  ggtitle("Mean Rating for each Group & Condition") + 
  theme(plot.title = element_text(hjust=0.5, lineheight=.8, face="bold")) +
  theme_classic()
gRat.3cond.plt

# Box plot
pRat.3cond.plt <- ggplot(pRat.3cond, aes(x=condition, y=rating, fill=group)) + 
  geom_boxplot() + 
  scale_fill_brewer(palette = "Paired") +
  xlab("Condition") + ylab("Rating") +
  ggtitle("Rating by Condition") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
pRat.3cond.plt

# All participants
pRat.3cond.s.plt <- ggplot(pRat.3cond, aes(x = subject, y = rating, fill=condition)) +
  geom_bar(stat = "identity", 
           position = "dodge", 
           colour = "black", # contour around each bar
           size = 0.2 # width of the contour line
  ) + 
  scale_fill_manual(values=cond.colors) +
  coord_cartesian(ylim=c(1.0, 5.0)) +
  xlab("Participant") + ylab("Mean Rating") +
  ggtitle("Mean Rating for each Participant") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
pRat.3cond.s.plt


## Causative only

# Subset causative condition
rat.caus <- all[which(all$condition == 'Causative'),]

# Order by group
rat.caus <- rat.caus[order(rat.caus$group),]

# Mean rating per participant
pRat.caus <- summarySE(rat.caus, measurevar="rating", 
                       groupvars = c("subject", "group", "age", "sex"),
                       na.rm = TRUE)

# All participants
pRat.caus.plt <- ggplot(pRat.caus, aes(x = subject, y = rating, fill=group)) +
  geom_bar(stat = "identity", 
           position = "dodge", 
           colour = "black", # contour around each bar
           size = 0.7 # width of the contour line
  ) + 
  scale_fill_brewer(palette = "Paired") +
  coord_cartesian(ylim=c(1.0, 5.0)) +
  xlab("Participant") + ylab("Mean Rating") +
  ggtitle("Mean Causative Rating for each Participant") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
pRat.caus.plt

## Pseudo-causative only

# Subset pseudo-causative condition
rat.pscaus <- all[which(all$condition == 'Pseudo-causative'),]

# Order by group
rat.pscaus <- rat.pscaus[order(rat.pscaus$group),]

# Mean rating per participant
pRat.pscaus <- summarySE(rat.pscaus, measurevar="rating", 
                       groupvars = c("subject", "group", "age", "sex"),
                       na.rm = TRUE)

# All participants
pRat.pscaus.plt <- ggplot(pRat.pscaus, aes(x = subject, y = rating, fill=group)) +
  geom_bar(stat = "identity", 
           position = "dodge", 
           colour = "black", # contour around each bar
           size = 0.7 # width of the contour line
  ) + 
  scale_fill_brewer(palette = "Paired") +
  coord_cartesian(ylim=c(1.0, 5.0)) +
  xlab("Participant") + ylab("Mean Rating") +
  ggtitle("Mean Pseudo-causative Rating for each Participant") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic()
pRat.pscaus.plt

# remake boxplot with only caus
pRat.3cond2 <- pRat.3cond %>%
  filter(condition == "Causative")
pRat.3cond.plt2 <- ggplot(pRat.3cond2, aes(x=group, y=rating, fill=group)) + 
  geom_boxplot() + 
  scale_fill_manual(values=c("slategray2", "steelblue1", "steelblue3",
                             "palegreen","palegreen3","palegreen4")) +
  xlab("Group") + ylab("Mean Rating") +
  ggtitle("Rating by Group") + 
  theme(plot.title = element_text(hjust = 0.5, lineheight=.8, face="bold")) +
  theme_classic() + 
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank())
pRat.3cond.plt2
```

```{r demographics export}
# make a pdf
pdf("6group_demo_plots.pdf", onefile = TRUE)
part.age.plt
part.sex.plt
pRat.plt
pRat.cond.plt
rat.cond.plt
gRat.cond.plt
gRat.3cond.plt
pRat.3cond.plt
pRat.3cond.s.plt
pRat.caus.plt
pRat.pscaus.plt
dev.off()

# save separately to png because plot is hard to see in pdf
ggsave("3condrating.png",pRat.3cond.s.plt,width = 12, height = 10)

# save remade group boxplot separately
ggsave("groupboxplot.png", pRat.3cond.plt2, width = 9, height = 6)
```


```{r ANOVA}
# Causative

# Run a linear model
model <- lm(rating ~ group, 
            data = pRat.caus, 
            contrasts = list(group = "contr.sum"))

# Run an ANOVA on the model
sstable <- Anova(model, type = 3) 
sstable

# Calculate effect size (Partial Eta-Squared)
sstable$pes <- c(sstable$'Sum Sq'[-nrow(sstable)], NA)/(sstable$'Sum Sq' + sstable$'Sum Sq'[nrow(sstable)]) # SS for each effect divided by the last SS (SS_residual)
anova.caus <- sstable

# Pretty table
#kable(sstable, "html", digits = 3, caption = "ANOVA with 4 Groups") %>%
#  kable_styling(bootstrap_options = c("striped", "hover"))

# Pseudo-causative

# Run a linear model
model <- lm(rating ~ group, 
            data = pRat.pscaus, 
            contrasts = list(group = "contr.sum"))

# Run an ANOVA on the model
sstable <- Anova(model, type = 3) 
sstable

# Calculate effect size (Partial Eta-Squared)
sstable$pes <- c(sstable$'Sum Sq'[-nrow(sstable)], NA)/(sstable$'Sum Sq' + sstable$'Sum Sq'[nrow(sstable)]) # SS for each effect divided by the last SS (SS_residual)
anova.pscaus <- sstable
```

```{r corr scatters}
# this chunk is for visualizing the correlation between certain variables

# create correlation scatterplots between Spanish freq and rating
pdf("corrscatter.pdf", onefile = T)
c = ggscatter(caus, x = "spnfreq", y = "rating", add = "reg.line",
              facet.by = "group", conf.int = T, conf.level = .95,
              cor.coef = T)
ggpar(c, main = "Causative Spanish Frequencies vs Rating")
p = ggscatter(pscaus, x = "spnfreq", y = "rating", add = "reg.line",
          facet.by = "group", conf.int = T, conf.level = .95,
          cor.coef = T)
ggpar(p, main = "Pseudo-Causative Spanish Frequencies vs Rating")
t = ggscatter(trans, x = "spnfreq", y = "rating", add = "reg.line",
          facet.by = "group", conf.int = T, conf.level = .95,
          cor.coef = T)
ggpar(t, main = "Transitive Spanish Frequencies vs Rating")
dev.off()

# separated by group does not give a strong correlation in each individual group, but altogether they do
pdf("zipfcorr.pdf", onefile = T)
c = ggscatter(caus, x = "zipf", y = "rating", add = "reg.line",
              facet.by = "group", conf.int = T, conf.level = .95,
              cor.coef = T)
ggpar(c, main = "Causative Spanish Frequencies vs Rating, Separated by Group")

c2 = ggscatter(caus, x = "zipf", y = "rating", add = "reg.line",
              conf.int = T, conf.level = .95,
              cor.coef = T)
ggpar(c2, main = "Causative Spanish Frequencies vs Rating")
dev.off()


# spread each group into its own column for next correlation plots
caus2 <- caus %>%
  group_by(verb, group) %>%
  summarise(rating) %>%
  select(group, rating, verb)
caus2 <- spread(caus2, key = group, value = rating)
names(caus2) <- c("verb", "HS", "EB", "LB", "SC", "ES", "EC")

# correlations between bilingual ratings and other bilingual groups
#pdf("BILvBILcorr.pdf", onefile = T)
c2hseb <- ggscatter(caus2, x = "HS", y = "EB",
                add = "reg.line", conf.int = T, conf.level = .95,
                cor.coef = T, label = "verb")
ggpar(c2hseb, main = "Correlation Between HS and EB", xlim = c(1,5), ylim = c(1,5))
c2hslb <- ggscatter(caus2, x = "HS", y = "LB",
                add = "reg.line", conf.int = T, conf.level = .95,
                cor.coef = T, label = "verb")
ggpar(c2hslb, main = "Correlation Between HS and LB", xlim = c(1,5), ylim = c(1,5))
c2eblb <- ggscatter(caus2, x = "EB", y = "LB",
                add = "reg.line", conf.int = T, conf.level = .95,
                cor.coef = T, label = "verb")
ggpar(c2eblb, main = "Correlation Between EB and LB", xlim = c(1,5), ylim = c(1,5))
# dev.off()

# correlations between sp monolingual ratings and bilinguals
#pdf("SPvBILcorr.pdf", onefile = T)
c2echs <- ggscatter(caus2, x = "EC", y = "HS", 
                add = "reg.line", conf.int = T, conf.level = .95,
                cor.coef = T, xlab = "English Controls", ylab = "Heritage Speakers")
ggpar(c2echs, main = "Correlation Between EC and HS")
c2eceb <- ggscatter(caus2, x = "EC", y = "EB", 
                add = "reg.line", conf.int = T, conf.level = .95,
                cor.coef = T, xlab = "English Controls", ylab = "Early Bilinguals")
ggpar(c2eceb, main = "Correlation Between EC and EB")
c2eclb <- ggscatter(caus2, x = "EC", y = "LB", 
                add = "reg.line", conf.int = T, conf.level = .95,
                cor.coef = T, xlab = "English Controls", ylab = "Late Bilinguals")
ggpar(c2eclb, main = "Correlation Between EC and LB")
#dev.off()

# correlations between en monolingual ratings and bilinguals
#pdf("ENvBILcorr.pdf", onefile = T)
c2eshs <- ggscatter(caus2, x = "ES", y = "HS", 
                add = "reg.line", conf.int = T, conf.level = .95,
                cor.coef = T, xlab = "Ecuador Spanish", ylab = "Heritage Speakers")
ggpar(c2eshs, main = "Correlation Between ES and HS")
c2eseb <- ggscatter(caus2, x = "ES", y = "EB", 
                add = "reg.line", conf.int = T, conf.level = .95,
                cor.coef = T, xlab = "Ecuador Spanish", ylab = "Early Bilinguals")
ggpar(c2eseb, main = "Correlation Between ES and EB")
c2eslb <- ggscatter(caus2, x = "ES", y = "LB", 
                add = "reg.line", conf.int = T, conf.level = .95,
                cor.coef = T, xlab = "Ecuador Spanish", ylab = "Late Bilinguals")
ggpar(c2eslb, main = "Correlation Between ES and LB")
#dev.off()

c2tot <- grid.arrange(c2echs, c2eceb, c2eclb,
                      c2eshs, c2eseb, c2eslb, ncol = 3,
                      top = text_grob("Correlation between Monolingual and Bilingual Ratings"))
ggsave("correlation.png", c2tot, width = 9, height = 6)



pairwise.t.test(caus$rating, caus$group, p.adj = "none")
anov <- aov(rating ~ group, caus)
TukeyHSD(anov)
```

```{r linear models}
# this chunk is used for linear models on zipf value (transformed lexical frequency) as a predictor for rating
zipflm <- lm(rating ~ zipf, caus)
summary(zipflm)
summary(lm(rating ~ group, caus))

summary(aov(rating ~ zipf + group + zipf*group, caus))

# as expected, bilinguals are significantly different for english controls but not for ecuador spanish
# check assumptions after every model
causES <- within(caus, group <- relevel(group, ref = "Ecuador Spanish"))
causEC <- within(caus, group <- relevel(group, ref = "English Controls"))
ESLM <- lm(rating ~ zipf + group, causES)
summary(ESLM)
plot(resid(ESLM))
ECLM <- lm(rating ~ group + zipf, causEC)
summary(ECLM)
plot(resid(ECLM))

anova(ECLM, zipflm)

pairwise.t.test(caus$rating, caus$group, p.adj = "none")
anov <- aov(rating ~ group, caus)
TukeyHSD(anov)
```


```{r lbq}
# bring lbq (language background variables) into analysis
lbq <- read.csv("Data.csv")
colnames(lbq) = c("subject","thinking",
                  "l1read","l1write","l1listen","l1speak","l1vocab","l1grammar","l1avg",
                  "l2read","l2write","l2listen","l2speak","l2vocab","l2grammar","l2avg",
                  "l3","multiYN","multi","CultureUS","CultureH","MoveUS","EngAoA")
# subject-level analysis
subjects <- all %>%
  filter(condition == "Causative") %>%
  group_by(subject, group) %>%
  summarise(avgrating = mean(rating, na.rm = T),
            sdrating = sd(rating, na.rm = T))
subjects <- merge(subjects, lbq, by = "subject")

# create a new categorical variable for language proficiency
attach(subjects)
subjects$proflevel[l1avg >= 6] <- "Strong"
subjects$proflevel[l1avg >= 3 & l1avg < 6] <- "Medium"
subjects$proflevel[l1avg < 3] <- "Weak"
detach(subjects)
# same with cultural affiliation
attach(subjects)
subjects$culturehlevel[CultureH >= 6] <- "Strong"
subjects$culturehlevel[CultureH >= 3 & CultureH < 6] <- "Medium"
subjects$culturehlevel[CultureH < 3] <- "Weak"
detach(subjects)

# visualize data
ggplot(subjects) +
  geom_bar(aes(x = group, y = avgrating, fill = proflevel),
               position = "dodge", stat = "summary", fun.y = "mean")

pdf("findings.pdf", onefile = T)
ggplot(subjects) +
  geom_point(aes(x = l1avg, y = avgrating, color = group))

ggplot(subjects) +
  geom_bar(aes(x = group, y = avgrating, fill = proflevel),
               position = "dodge", stat = "summary", fun.y = "mean")


ggplot(subjects) +
  geom_bar(aes(group, y = avgrating, fill = thinking),
               position = "dodge", stat = "summary", fun.y = "mean")

ggplot(subjects) + 
  geom_col(aes(x = factor(CultureUS), y = avgrating), position = "dodge") +
  facet_grid(. ~ group) +
  ggtitle("Cultural affiliation bar chart")

ggplot(subjects, aes(x=l1avg)) + geom_histogram(binwidth=.5) +
  facet_grid(. ~ group) +
  ggtitle("L1 proficiency by group")

ggplot(subjects, aes(x=l2avg)) + geom_histogram(binwidth=.5) +
  facet_grid(. ~ group) +
  ggtitle("L1 proficiency by group")
dev.off()
  
# trim out fat from lbq
modellbq <- lbq %>%
  select(subject, MoveUS, EngAoA, l1avg, l2avg)

# merge trial level data with verb data
all_new <- merge(x = all, y = allverbn, by = "verb", all.x = TRUE)
# instead of using averaged ratings, treat ratings as an ordinal categorical with 5 levels
caus_new <- all_new %>%
  filter(condition == "Causative")
caus_new$rating <- factor(caus_new$rating, ordered = TRUE, levels = c("1","2","3","4","5"))
# no lbq for Ecuador, will remove by merging
caus_new <- merge(caus_new, lbq, by = "subject")
caus_bil <- caus_new %>%
  filter(group %in% c("Heritage Speakers", "Early Bilinguals", "Late Bilinguals"))

# linear mixed effects models
zipf_lm <- lmer(rating ~ group + (1|verb) + (1|subject), data = caus_new)
zipf_full <- lmer(rating ~ zipf + group + (1|verb) + (1|subject), data = caus_new)
anova(zipf_lm, zipf_full)

zipf_inter <- lmer(rating ~ zipf * group + (1|verb) + (zipf|subject), data = caus_new)
summary(zipf_lm)
summary(zipf_full)

anova(zipf_full, zipf_inter)
zipf_only <- glmer(rating ~ zipf + (1|verb) + (1|subject), family = poisson, data = caus_new)

# rating is now a categorical variable, use clmm for ordinal mixed effects regression
zipf_clmm <- clmm(rating ~ zipf + stimNum + group + group:stimNum + (1|verb) + (1|subject), data = caus_new)
zipf_clmm <- clmm(rating ~ zipf + stimNum + EngAoA + MoveUS + l1avg + l2avg + (1|verb) + (1|subject), data = caus_bil)
summary(zipf_clmm)
```

